// (Same as your verified M2 implementation)
// ————————————————
import type { Card } from "@referee/referee_api";
const RANK_RE = /^(\d+|[JQKA])/;
const SUIT_RE = /([SHDC])$/;
export const rankVal = (c: Card): number => { const r = c.match(RANK_RE)![1]; if (r === "A") return 1; if (r === "J"||r==="Q"||r==="K") return 10; return parseInt(r,10) };
export const rankNum = (c: Card): number => { const r = c.match(RANK_RE)![1]; if (r === "A") return 1; if (r === "J") return 11; if (r === "Q") return 12; if (r === "K") return 13; return parseInt(r,10) };
export const rankKey = (c: Card): string => c.match(RANK_RE)![1];
export const suitKey = (c: Card): string => c.match(SUIT_RE)![1];
export function canPlayCard(card: Card, peggingCount: number): boolean { return peggingCount + rankVal(card) <= 31 }
function scorePairs(tail: Card[]){ if (tail.length<2) return {points:0}; const last = rankKey(tail[tail.length-1]); let same=1; for(let i=tail.length-2;i>=0;i--){ if(rankKey(tail[i])===last) same++; else break } if(same===2) return {points:2,note:"pair for 2"}; if(same===3) return {points:6,note:"three of a kind for 6"}; if(same>=4) return {points:12,note:"four of a kind for 12"}; return {points:0} }
function isConsecutive(nums:number[]){ nums.sort((a,b)=>a-b); for(let i=1;i<nums.length;i++) if(nums[i]!==nums[i-1]+1) return false; return true }
function scoreRun(stack: Card[]){ const n=stack.length; for(let len=Math.min(7,n); len>=3; len--){ const tail=stack.slice(n-len); const ranks=tail.map(rankKey); const uniq=new Set(ranks); if(uniq.size!==len) continue; const vals=[...uniq].map(r=>rankNum((r+"S") as Card)); if(isConsecutive(vals)) return {points:len,note:`run of ${len}`} } return {points:0} }
export function scorePegPlay(stack: Card[], newCount: number){ let points=0; const notes:string[]=[]; if(newCount===15){ points+=2; notes.push("fifteen for 2") } if(newCount===31){ points+=2; notes.push("thirty-one for 2") } const pair=scorePairs(stack); if(pair.points){ points+=pair.points; notes.push(pair.note!) } if(!pair.points){ const run=scoreRun(stack); if(run.points){ points+=run.points; notes.push(run.note!) } } return { points, announce: points>0?notes.join(", ") : undefined } }
function allFifteens(cards:Card[]){ let count=0; const n=cards.length; for(let i=1;i<(1<<n);i++){ let sum=0; for(let j=0;j<n;j++){ if((i>>j)&1) sum+=rankVal(cards[j]) } if(sum===15) count++ } return count? {points:count*2, note:`${count} fifteen(s) for ${count*2}`} : {points:0, note:""} }
function pairPoints(cards:Card[]){ const counts:Record<string,number>={}; for(const c of cards){ const r=rankKey(c); counts[r]=(counts[r]||0)+1 } let points=0; const notes:string[]=[]; for(const r in counts){ if(counts[r]===2){ points+=2; notes.push("pair for 2") } else if(counts[r]===3){ points+=6; notes.push("three of a kind for 6") } else if(counts[r]===4){ points+=12; notes.push("four of a kind for 12") } } return {points, note: notes.join(", ")} }
function runPoints(cards:Card[]){ const ranks=cards.map(rankNum).sort((a,b)=>a-b); const rankCounts:Record<number,number>={}; cards.forEach(c=>{ const r=rankNum(c); rankCounts[r]=(rankCounts[r]||0)+1 }); const unique=[...new Set(ranks)]; let points=0; let runNotes=""; let i=0; while(i<unique.length){ let j=i; while(j<unique.length-1 && unique[j+1]===unique[j]+1) j++; const run=unique.slice(i,j+1); if(run.length>=3){ let mult=1; for(const r of run) mult*=rankCounts[r]; const len=run.length; points += len*mult; if(mult===1) runNotes=`run of ${len} for ${len}`; else if(mult===2) runNotes=`double run of ${len} for ${len*2}`; else if(mult===3) runNotes=`triple run of ${len} for ${len*3}`; else if(mult===4) runNotes=`double-double run of ${len} for ${len*4}`; i=j; } i++; } return {points, note: runNotes} }
function flushPoints(hand:Card[], starter:Card, isCrib:boolean){ const suit = suitKey(hand[0]); if(!hand.every(c=>suitKey(c)===suit)) return {points:0, note:""}; if(suitKey(starter)===suit) return {points:5, note:"flush of 5 for 5"}; return isCrib ? {points:0, note:""} : {points:4, note:"flush of 4 for 4"} }
function nobs(hand:Card[], starter:Card){ const ss = suitKey(starter); const has = hand.some(c=>rankKey(c)==='J' && suitKey(c)===ss); return { points: has?1:0, note: has?"nobs for 1":"" }
}
function countCards(hand:Card[], starter:Card, isCrib:boolean){ const all=[...hand, starter]; const breakdown:string[]=[]; let total=0; const p15=allFifteens(all); if(p15.points){ total+=p15.points; breakdown.push(p15.note) } const pPairs=pairPoints(all); if(pPairs.points){ total+=pPairs.points; breakdown.push(pPairs.note) } const pRuns=runPoints(all); if(pRuns.points){ total+=pRuns.points; breakdown.push(pRuns.note) } const pFlush=flushPoints(hand, starter, isCrib); if(pFlush.points){ total+=pFlush.points; breakdown.push(pFlush.note) } const pNobs=nobs(hand, starter); if(pNobs.points){ total+=pNobs.points; breakdown.push(pNobs.note) } return { points: total, breakdown: breakdown.filter(Boolean) }
}
export function countHand(hand:Card[], starter:Card){ return countCards(hand, starter, false) }
export function countCrib(crib:Card[], starter:Card){ return countCards(crib, starter, true) }
